ASPECT_PAIRS = {
    "читать": {"perfective": "прочитать", "type": "prefix", "prefix": "про-"},
    "прочитать": {"imperfective": "читать", "type": "prefix", "prefix": "про-"},
    "делать": {"perfective": "сделать", "type": "prefix", "prefix": "с-"},
    "сделать": {"imperfective": "делать", "type": "prefix", "prefix": "с-"},
    "играть": {"perfective": "поиграть", "type": "prefix", "prefix": "по-"},
    "поиграть": {"imperfective": "играть", "type": "prefix", "prefix": "по-"},
    "работать": {"perfective": "поработать", "type": "prefix", "prefix": "по-"},
    "поработать": {"imperfective": "работать", "type": "prefix", "prefix": "по-"},
    "думать": {"perfective": "подумать", "type": "prefix", "prefix": "по-"},
    "подумать": {"imperfective": "думать", "type": "prefix", "prefix": "по-"},
    "знать": {"perfective": "узнать", "type": "prefix", "prefix": "у-"},
    "узнать": {"imperfective": "знать", "type": "prefix", "prefix": "у-"},
    "понимать": {"perfective": "понять", "type": "suppletive", "note": "Different stem (понима- vs поня-)"},
    "понять": {"imperfective": "понимать", "type": "suppletive", "note": "Different stem (поня- vs понима-)"},
    "слушать": {"perfective": "послушать", "type": "prefix", "prefix": "по-"},
    "послушать": {"imperfective": "слушать", "type": "prefix", "prefix": "по-"},
    "гулять": {"perfective": "погулять", "type": "prefix", "prefix": "по-"},
    "погулять": {"imperfective": "гулять", "type": "prefix", "prefix": "по-"},
    "кушать": {"perfective": "покушать", "type": "prefix", "prefix": "по-"},
    "покушать": {"imperfective": "кушать", "type": "prefix", "prefix": "по-"},
    "обедать": {"perfective": "пообедать", "type": "prefix", "prefix": "по-"},
    "пообедать": {"imperfective": "обедать", "type": "prefix", "prefix": "по-"},
    "ужинать": {"perfective": "поужинать", "type": "prefix", "prefix": "по-"},
    "поужинать": {"imperfective": "ужинать", "type": "prefix", "prefix": "по-"},
    "завтракать": {"perfective": "позавтракать", "type": "prefix", "prefix": "по-"},
    "позавтракать": {"imperfective": "завтракать", "type": "prefix", "prefix": "по-"},
    "отдыхать": {"perfective": "отдохнуть", "type": "suppletive", "note": "Different stem (отдыха- vs отдохн-)"},
    "отдохнуть": {"imperfective": "отдыхать", "type": "suppletive", "note": "Different stem (отдохн- vs отдыха-)"},
    "встречать": {"perfective": "встретить", "type": "suppletive", "note": "Different stem (встреча- vs встрет-)"},
    "встретить": {"imperfective": "встречать", "type": "suppletive", "note": "Different stem (встрет- vs встреча-)"},
    "отвечать": {"perfective": "ответить", "type": "suppletive", "note": "Different stem (отвеча- vs ответ-)"},
    "ответить": {"imperfective": "отвечать", "type": "suppletive", "note": "Different stem (ответ- vs отвеча-)"},
    "спрашивать": {"perfective": "спросить", "type": "suppletive", "note": "Different stem (спрашива- vs спрос-)"},
    "спросить": {"imperfective": "спрашивать", "type": "suppletive", "note": "Different stem (спрос- vs спрашива-)"},
    "повторять": {"perfective": "повторить", "type": "prefix", "prefix": "по-"},
    "повторить": {"imperfective": "повторять", "type": "prefix", "prefix": "по-"},
    "изучать": {"perfective": "изучить", "type": "prefix", "prefix": "из-"},
    "изучить": {"imperfective": "изучать", "type": "prefix", "prefix": "из-"},
    "начинать": {"perfective": "начать", "type": "suppletive", "note": "Different stem (начина- vs начн-)"},
    "начать": {"imperfective": "начинать", "type": "suppletive", "note": "Different stem (начн- vs начина-)"},
    "кончать": {"perfective": "кончить", "type": "suppletive", "note": "Different stem (конча- vs конч-)"},
    "кончить": {"imperfective": "кончать", "type": "suppletive", "note": "Different stem (конч- vs конча-)"},
    "мечтать": {"perfective": "помечтать", "type": "prefix", "prefix": "по-"},
    "помечтать": {"imperfective": "мечтать", "type": "prefix", "prefix": "по-"},
    "желать": {"perfective": "пожелать", "type": "prefix", "prefix": "по-"},
    "пожелать": {"imperfective": "желать", "type": "prefix", "prefix": "по-"},
    "менять": {"perfective": "поменять", "type": "prefix", "prefix": "по-"},
    "поменять": {"imperfective": "менять", "type": "prefix", "prefix": "по-"},
    "терять": {"perfective": "потерять", "type": "prefix", "prefix": "по-"},
    "потерять": {"imperfective": "терять", "type": "prefix", "prefix": "по-"},
    "бросать": {"perfective": "бросить", "type": "suppletive", "note": "Different stem (броса- vs брос-)"},
    "бросить": {"imperfective": "бросать", "type": "suppletive", "note": "Different stem (брос- vs броса-)"},
    "кидать": {"perfective": "кинуть", "type": "suppletive", "note": "Different stem (кида- vs кин-)"},
    "кинуть": {"imperfective": "кидать", "type": "suppletive", "note": "Different stem (кин- vs кида-)"},
    "ломать": {"perfective": "сломать", "type": "prefix", "prefix": "с-"},
    "сломать": {"imperfective": "ломать", "type": "prefix", "prefix": "с-"},
    "хватать": {"perfective": "хватить", "type": "suppletive", "note": "Different stem (хвата- vs хват-)"},
    "хватить": {"imperfective": "хватать", "type": "suppletive", "note": "Different stem (хват- vs хвата-)"},
    "купать": {"perfective": "искупать", "type": "prefix", "prefix": "ис-"},
    "искупать": {"imperfective": "купать", "type": "prefix", "prefix": "ис-"},
    "опаздывать": {"perfective": "опоздать", "type": "suppletive", "note": "Different stem (опаздыва- vs опозда-)"},
    "опоздать": {"imperfective": "опаздывать", "type": "suppletive", "note": "Different stem (опозда- vs опаздыва-)"},
    "уметь": {"perfective": "суметь", "type": "prefix", "prefix": "с-"},
    "суметь": {"imperfective": "уметь", "type": "prefix", "prefix": "с-"},
    "жалеть": {"perfective": "пожалеть", "type": "prefix", "prefix": "по-"},
    "пожалеть": {"imperfective": "жалеть", "type": "prefix", "prefix": "по-"},
    "худеть": {"perfective": "похудеть", "type": "prefix", "prefix": "по-"},
    "похудеть": {"imperfective": "худеть", "type": "prefix", "prefix": "по-"},
    "толстеть": {"perfective": "потолстеть", "type": "prefix", "prefix": "по-"},
    "потолстеть": {"imperfective": "толстеть", "type": "prefix", "prefix": "по-"},
    "успеть": {"imperfective": "успевать", "type": "suppletive", "note": "Different stem (успе- vs успева-)"},
    "успевать": {"perfective": "успеть", "type": "suppletive", "note": "Different stem (успева- vs успе-)"},
    "поспеть": {"imperfective": "поспевать", "type": "suppletive", "note": "Different stem (поспе- vs послева-)"},
    "поспевать": {"perfective": "поспеть", "type": "suppletive", "note": "Different stem (поспева- vs после-)"},
    "созреть": {"imperfective": "созревать", "type": "suppletive", "note": "Different stem (созре- vs созрева-)"},
    "созревать": {"perfective": "созреть", "type": "suppletive", "note": "Different stem (созрева- vs созре-)"},
    "бегать": {"perfective": "побегать", "type": "prefix", "prefix": "по-"},
    "побегать": {"imperfective": "бегать", "type": "prefix", "prefix": "по-"},
    "плавать": {"perfective": "поплавать", "type": "prefix", "prefix": "по-"},
    "поплавать": {"imperfective": "плавать", "type": "prefix", "prefix": "по-"},
    "летать": {"perfective": "полетать", "type": "prefix", "prefix": "по-"},
    "полетать": {"imperfective": "летать", "type": "prefix", "prefix": "по-"},
    "лазать": {"perfective": "полазать", "type": "prefix", "prefix": "по-"},
    "полазать": {"imperfective": "лазать", "type": "prefix", "prefix": "по-"},
    "ползать": {"perfective": "поползать", "type": "prefix", "prefix": "по-"},
    "поползать": {"imperfective": "ползать", "type": "prefix", "prefix": "по-"},
    "писать": {"perfective": "написать", "type": "prefix", "prefix": "на-"},
    "написать": {"imperfective": "писать", "type": "prefix", "prefix": "на-"},
    "искать": {"perfective": "поискать", "type": "prefix", "prefix": "по-"},
    "поискать": {"imperfective": "искать", "type": "prefix", "prefix": "по-"},
    "резать": {"perfective": "порезать", "type": "prefix", "prefix": "по-"},
    "порезать": {"imperfective": "резать", "type": "prefix", "prefix": "по-"},
    "мазать": {"perfective": "намазать", "type": "prefix", "prefix": "на-"},
    "намазать": {"imperfective": "мазать", "type": "prefix", "prefix": "на-"},
    "плакать": {"perfective": "заплакать", "type": "prefix", "prefix": "за-"},
    "заплакать": {"imperfective": "плакать", "type": "prefix", "prefix": "за-"},
    "пахать": {"perfective": "вспахать", "type": "prefix", "prefix": "вс-"},
    "вспахать": {"imperfective": "пахать", "type": "prefix", "prefix": "вс-"},
    "скакать": {"perfective": "поскакать", "type": "prefix", "prefix": "по-"},
    "поскакать": {"imperfective": "скакать", "type": "prefix", "prefix": "по-"},
    "сказать": {"imperfective": "говорить", "type": "suppletive", "note": "Completely different roots (сказа- vs говор-)"},
    "рассказать": {"imperfective": "рассказывать", "type": "suppletive", "note": "Different stem (рассказа- vs рассказыва-)"},
    "рассказывать": {"perfective": "рассказать", "type": "suppletive", "note": "Different stem (рассказыва- vs рассказа-)"},
    "рисовать": {"perfective": "нарисовать", "type": "prefix", "prefix": "на-"},
    "нарисовать": {"imperfective": "рисовать", "type": "prefix", "prefix": "на-"},
    "танцевать": {"perfective": "потанцевать", "type": "prefix", "prefix": "по-"},
    "потанцевать": {"imperfective": "танцевать", "type": "prefix", "prefix": "по-"},
    "целовать": {"perfective": "поцеловать", "type": "prefix", "prefix": "по-"},
    "поцеловать": {"imperfective": "целовать", "type": "prefix", "prefix": "по-"},
    "советовать": {"perfective": "посоветовать", "type": "prefix", "prefix": "по-"},
    "посоветовать": {"imperfective": "советовать", "type": "prefix", "prefix": "по-"},
    "требовать": {"perfective": "потребовать", "type": "prefix", "prefix": "по-"},
    "потребовать": {"imperfective": "требовать", "type": "prefix", "prefix": "по-"},
    "чувствовать": {"perfective": "почувствовать", "type": "prefix", "prefix": "по-"},
    "почувствовать": {"imperfective": "чувствовать", "type": "prefix", "prefix": "по-"},
    "интересовать": {"perfective": "заинтересовать", "type": "prefix", "prefix": "за-"},
    "заинтересовать": {"imperfective": "интересовать", "type": "prefix", "prefix": "за-"},
    "участвовать": {"perfective": "поучаствовать", "type": "prefix", "prefix": "по-"},
    "поучаствовать": {"imperfective": "участвовать", "type": "prefix", "prefix": "по-"},
    "существовать": {"perfective": "просуществовать", "type": "prefix", "prefix": "про-"},
    "просуществовать": {"imperfective": "существовать", "type": "prefix", "prefix": "про-"},
    "рекомендовать": {"perfective": "порекомендовать", "type": "prefix", "prefix": "по-"},
    "порекомендовать": {"imperfective": "рекомендовать", "type": "prefix", "prefix": "по-"},
    "воевать": {"perfective": "повоевать", "type": "prefix", "prefix": "по-"},
    "повоевать": {"imperfective": "воевать", "type": "prefix", "prefix": "по-"},
    "ночевать": {"perfective": "переночевать", "type": "prefix", "prefix": "пере-"},
    "переночевать": {"imperfective": "ночевать", "type": "prefix", "prefix": "пере-"},
    "попробовать": {"imperfective": "пробовать", "type": "prefix", "prefix": "по-"},
    "пробовать": {"perfective": "попробовать", "type": "prefix", "prefix": "по-"},
    "прыгать": {"perfective": "прыгнуть", "type": "suppletive", "note": "Different suffix (-а- vs -ну-)"},
    "прыгнуть": {"imperfective": "прыгать", "type": "suppletive", "note": "Different suffix (-ну- vs -а-)"},
    "кричать": {"perfective": "крикнуть", "type": "suppletive", "note": "Different suffix (-ча- vs -кн-)"},
    "крикнуть": {"imperfective": "кричать", "type": "suppletive", "note": "Different suffix (-кн- vs -ча-)"},
    "стучать": {"perfective": "постучать", "type": "prefix", "prefix": "по-"},
    "постучать": {"imperfective": "стучать", "type": "prefix", "prefix": "по-"},
    "толкать": {"perfective": "толкнуть", "type": "suppletive", "note": "Different suffix (-ка- vs -кну-)"},
    "толкнуть": {"imperfective": "толкать", "type": "suppletive", "note": "Different suffix (-кну- vs -ка-)"},
    "махать": {"perfective": "махнуть", "type": "suppletive", "note": "Different stem (маха- vs махн-)"},
    "махнуть": {"imperfective": "махать", "type": "suppletive", "note": "Different stem (махн- vs маха-)"},
    "вернуть": {"imperfective": "возвращать", "type": "suppletive", "note": "Different roots (вер- vs возвращ-)"},
    "возвращать": {"perfective": "вернуть", "type": "suppletive", "note": "Different roots (возвраща- vs вер-)"},
    "говорить": {"perfective": "сказать", "type": "suppletive", "note": "Completely different roots (говор- vs скаж-)"},
    "любить": {"perfective": "полюбить", "type": "prefix", "prefix": "по-"},
    "полюбить": {"imperfective": "любить", "type": "prefix", "prefix": "по-"},
    "носить": {"perfective": "поносить", "type": "prefix", "prefix": "по-"},
    "поносить": {"imperfective": "носить", "type": "prefix", "prefix": "по-"},
    "ходить": {"perfective": "сходить", "type": "prefix", "prefix": "с-"},
    "сходить": {"imperfective": "ходить", "type": "prefix", "prefix": "с-"},
    "просить": {"perfective": "попросить", "type": "prefix", "prefix": "по-"},
    "попросить": {"imperfective": "просить", "type": "prefix", "prefix": "по-"},
    "возить": {"perfective": "повозить", "type": "prefix", "prefix": "по-"},
    "повозить": {"imperfective": "возить", "type": "prefix", "prefix": "по-"},
    "платить": {"perfective": "заплатить", "type": "prefix", "prefix": "за-"},
    "заплатить": {"imperfective": "платить", "type": "prefix", "prefix": "за-"},
    "крутить": {"perfective": "закрутить", "type": "prefix", "prefix": "за-"},
    "закрутить": {"imperfective": "крутить", "type": "prefix", "prefix": "за-"},
    "варить": {"perfective": "сварить", "type": "prefix", "prefix": "с-"},
    "сварить": {"imperfective": "варить", "type": "prefix", "prefix": "с-"},
    "дарить": {"perfective": "подарить", "type": "prefix", "prefix": "по-"},
    "подарить": {"imperfective": "дарить", "type": "prefix", "prefix": "по-"},
    "готовить": {"perfective": "приготовить", "type": "prefix", "prefix": "при-"},
    "приготовить": {"imperfective": "готовить", "type": "prefix", "prefix": "при-"},
    "ловить": {"perfective": "поймать", "type": "suppletive", "note": "Completely different roots (лов- vs пойма-)"},
    "поймать": {"imperfective": "ловить", "type": "suppletive", "note": "Completely different roots (пойма- vs лов-)"},
    "ставить": {"perfective": "поставить", "type": "prefix", "prefix": "по-"},
    "поставить": {"imperfective": "ставить", "type": "prefix", "prefix": "по-"},
    "тратить": {"perfective": "потратить", "type": "prefix", "prefix": "по-"},
    "потратить": {"imperfective": "тратить", "type": "prefix", "prefix": "по-"},
    "пустить": {"imperfective": "пускать", "type": "suppletive", "note": "Different stem (пуст- vs пуска-)"},
    "пускать": {"perfective": "пустить", "type": "suppletive", "note": "Different stem (пуска- vs пуст-)"},
    "простить": {"imperfective": "прощать", "type": "suppletive", "note": "Different stem (прост- vs проща-)"},
    "прощать": {"perfective": "простить", "type": "suppletive", "note": "Different stem (проща- vs прост-)"},
    "грустить": {"perfective": "загрустить", "type": "prefix", "prefix": "за-"},
    "загрустить": {"imperfective": "грустить", "type": "prefix", "prefix": "за-"},
    "чистить": {"perfective": "почистить", "type": "prefix", "prefix": "по-"},
    "почистить": {"imperfective": "чистить", "type": "prefix", "prefix": "по-"},
    "ездить": {"perfective": "поездить", "type": "prefix", "prefix": "по-"},
    "поездить": {"imperfective": "ездить", "type": "prefix", "prefix": "по-"},
    "объяснить": {"imperfective": "объяснять", "type": "prefix", "prefix": "об-"},
    "объяснять": {"perfective": "объяснить", "type": "prefix", "prefix": "об-"},
    "сидеть": {"perfective": "посидеть", "type": "prefix", "prefix": "по-"},
    "посидеть": {"imperfective": "сидеть", "type": "prefix", "prefix": "по-"},
    "висеть": {"perfective": "провисеть", "type": "prefix", "prefix": "про-"},
    "провисеть": {"imperfective": "висеть", "type": "prefix", "prefix": "про-"},
    "лететь": {"perfective": "полететь", "type": "prefix", "prefix": "по-"},
    "полететь": {"imperfective": "лететь", "type": "prefix", "prefix": "по-"},
    "шуметь": {"perfective": "зашуметь", "type": "prefix", "prefix": "за-"},
    "зашуметь": {"imperfective": "шуметь", "type": "prefix", "prefix": "за-"},
    "смотреть": {"perfective": "посмотреть", "type": "prefix", "prefix": "по-"},
    "посмотреть": {"imperfective": "смотреть", "type": "prefix", "prefix": "по-"},
    "видеть": {"perfective": "увидеть", "type": "prefix", "prefix": "у-"},
    "увидеть": {"imperfective": "видеть", "type": "prefix", "prefix": "у-"},
    "ненавидеть": {"perfective": "возненавидеть", "type": "prefix", "prefix": "воз-"},
    "возненавидеть": {"imperfective": "ненавидеть", "type": "prefix", "prefix": "воз-"},
    "терпеть": {"perfective": "потерпеть", "type": "prefix", "prefix": "по-"},
    "потерпеть": {"imperfective": "терпеть", "type": "prefix", "prefix": "по-"},
    "обидеть": {"imperfective": "обижать", "type": "suppletive", "note": "Different stem (обид- vs обижа-)"},
    "обижать": {"perfective": "обидеть", "type": "suppletive", "note": "Different stem (обижа- vs обид-)"},
    "зависеть": {"perfective": "позависеть", "type": "prefix", "prefix": "по-"},
    "позависеть": {"imperfective": "зависеть", "type": "prefix", "prefix": "по-"},
    "вертеть": {"perfective": "завертеть", "type": "prefix", "prefix": "за-"},
    "завертеть": {"imperfective": "вертеть", "type": "prefix", "prefix": "за-"},
    "слышать": {"perfective": "услышать", "type": "prefix", "prefix": "у-"},
    "услышать": {"imperfective": "слышать", "type": "prefix", "prefix": "у-"},
    "держать": {"perfective": "подержать", "type": "prefix", "prefix": "по-"},
    "подержать": {"imperfective": "держать", "type": "prefix", "prefix": "по-"},
    "дышать": {"perfective": "подышать", "type": "prefix", "prefix": "по-"},
    "подышать": {"imperfective": "дышать", "type": "prefix", "prefix": "по-"},
    "гнать": {"perfective": "погнать", "type": "prefix", "prefix": "по-"},
    "погнать": {"imperfective": "гнать", "type": "prefix", "prefix": "по-"},
    "лежать": {"perfective": "полежать", "type": "prefix", "prefix": "по-"},
    "полежать": {"imperfective": "лежать", "type": "prefix", "prefix": "по-"},
    "молчать": {"perfective": "помолчать", "type": "prefix", "prefix": "по-"},
    "помолчать": {"imperfective": "молчать", "type": "prefix", "prefix": "по-"},
    "звучать": {"perfective": "прозвучать", "type": "prefix", "prefix": "про-"},
    "прозвучать": {"imperfective": "звучать", "type": "prefix", "prefix": "про-"},
    "спать": {"perfective": "поспать", "type": "prefix", "prefix": "по-"},
    "поспать": {"imperfective": "спать", "type": "prefix", "prefix": "по-"},
    "купить": {"imperfective": "покупать", "type": "suppletive", "note": "Different stem (куп- vs покупа-)"},
    "покупать": {"perfective": "купить", "type": "suppletive", "note": "Different stem (покупа- vs куп-)"},
    "закончить": {"imperfective": "заканчивать", "type": "suppletive", "note": "Different stem (законч- vs заканчива-)"},
    "заканчивать": {"perfective": "закончить", "type": "suppletive", "note": "Different stem (заканчива- vs законч-)"},
    "бежать": {"perfective": "побежать", "type": "prefix", "prefix": "по-"},
    "побежать": {"imperfective": "бежать", "type": "prefix", "prefix": "по-"},
    "хотеть": {"perfective": "захотеть", "type": "prefix", "prefix": "за-"},
    "захотеть": {"imperfective": "хотеть", "type": "prefix", "prefix": "за-"},
    "ехать": {"perfective": "поехать", "type": "prefix", "prefix": "по-"},
    "поехать": {"imperfective": "ехать", "type": "prefix", "prefix": "по-"},
    "идти": {"perfective": "пойти", "type": "suppletive", "note": "Different roots (ид- vs пойд-)"},
    "пойти": {"imperfective": "идти", "type": "suppletive", "note": "Different roots (пойд- vs ид-)"},
    "прийти": {"imperfective": "приходить", "type": "suppletive", "note": "Different roots (прид- vs приход-)"},
    "приходить": {"perfective": "прийти", "type": "suppletive", "note": "Different roots (приход- vs прид-)"},
    "пройти": {"imperfective": "проходить", "type": "suppletive", "note": "Different roots (пройд- vs проход-)"},
    "проходить": {"perfective": "пройти", "type": "suppletive", "note": "Different roots (проход- vs пройд-)"},
    "найти": {"imperfective": "находить", "type": "suppletive", "note": "Different roots (найд- vs наход-)"},
    "находить": {"perfective": "найти", "type": "suppletive", "note": "Different roots (наход- vs найд-)"},
    "нести": {"perfective": "понести", "type": "prefix", "prefix": "по-"},
    "понести": {"imperfective": "нести", "type": "prefix", "prefix": "по-"},
    "везти": {"perfective": "повезти", "type": "prefix", "prefix": "по-"},
    "повезти": {"imperfective": "везти", "type": "prefix", "prefix": "по-"},
    "вести": {"perfective": "повести", "type": "prefix", "prefix": "по-"},
    "повести": {"imperfective": "вести", "type": "prefix", "prefix": "по-"},
    "ползти": {"perfective": "поползти", "type": "prefix", "prefix": "по-"},
    "поползти": {"imperfective": "ползти", "type": "prefix", "prefix": "по-"},
    "расти": {"perfective": "вырасти", "type": "prefix", "prefix": "вы-"},
    "вырасти": {"imperfective": "расти", "type": "prefix", "prefix": "вы-"},
    "цвести": {"perfective": "зацвести", "type": "prefix", "prefix": "за-"},
    "зацвести": {"imperfective": "цвести", "type": "prefix", "prefix": "за-"},
    "класть": {"perfective": "положить", "type": "suppletive", "note": "Completely different roots (клад- vs полож-)"},
    "положить": {"imperfective": "класть", "type": "suppletive", "note": "Completely different roots (полож- vs клад-)"},
    "лезть": {"perfective": "полезть", "type": "prefix", "prefix": "по-"},
    "полезть": {"imperfective": "лезть", "type": "prefix", "prefix": "по-"},
    "мочь": {"perfective": "смочь", "type": "prefix", "prefix": "с-"},
    "смочь": {"imperfective": "мочь", "type": "prefix", "prefix": "с-"},
    "помочь": {"imperfective": "помогать", "type": "suppletive", "note": "Different stem (помог- vs помога-)"},
    "помогать": {"perfective": "помочь", "type": "suppletive", "note": "Different stem (помога- vs помог-)"},
    "беречь": {"perfective": "сберечь", "type": "prefix", "prefix": "с-"},
    "сберечь": {"imperfective": "беречь", "type": "prefix", "prefix": "с-"},
    "печь": {"perfective": "испечь", "type": "prefix", "prefix": "ис-"},
    "испечь": {"imperfective": "печь", "type": "prefix", "prefix": "ис-"},
    "течь": {"perfective": "потечь", "type": "prefix", "prefix": "по-"},
    "потечь": {"imperfective": "течь", "type": "prefix", "prefix": "по-"},
    "сечь": {"perfective": "посечь", "type": "prefix", "prefix": "по-"},
    "посечь": {"imperfective": "сечь", "type": "prefix", "prefix": "по-"},
    "жечь": {"perfective": "сжечь", "type": "prefix", "prefix": "с-"},
    "сжечь": {"imperfective": "жечь", "type": "prefix", "prefix": "с-"},
    "стричь": {"perfective": "постричь", "type": "prefix", "prefix": "по-"},
    "постричь": {"imperfective": "стричь", "type": "prefix", "prefix": "по-"},
    "влечь": {"perfective": "привлечь", "type": "prefix", "prefix": "при-"},
    "привлечь": {"imperfective": "влечь", "type": "prefix", "prefix": "при-"},
    "бить": {"perfective": "побить", "type": "prefix", "prefix": "по-"},
    "побить": {"imperfective": "бить", "type": "prefix", "prefix": "по-"},
    "пить": {"perfective": "выпить", "type": "prefix", "prefix": "вы-"},
    "выпить": {"imperfective": "пить", "type": "prefix", "prefix": "вы-"},
    "лить": {"perfective": "вылить", "type": "prefix", "prefix": "вы-"},
    "вылить": {"imperfective": "лить", "type": "prefix", "prefix": "вы-"},
    "шить": {"perfective": "сшить", "type": "prefix", "prefix": "с-"},
    "сшить": {"imperfective": "шить", "type": "prefix", "prefix": "с-"},
    "вить": {"perfective": "свить", "type": "prefix", "prefix": "с-"},
    "свить": {"imperfective": "вить", "type": "prefix", "prefix": "с-"},
    "брить": {"perfective": "побрить", "type": "prefix", "prefix": "по-"},
    "побрить": {"imperfective": "брить", "type": "prefix", "prefix": "по-"},
    "жить": {"perfective": "прожить", "type": "prefix", "prefix": "про-"},
    "прожить": {"imperfective": "жить", "type": "prefix", "prefix": "про-"},
    "плыть": {"perfective": "поплыть", "type": "prefix", "prefix": "по-"},
    "поплыть": {"imperfective": "плыть", "type": "prefix", "prefix": "по-"},
    "слыть": {"perfective": "прослыть", "type": "prefix", "prefix": "про-"},
    "прослыть": {"imperfective": "слыть", "type": "prefix", "prefix": "про-"},
    "петь": {"perfective": "спеть", "type": "prefix", "prefix": "с-"},
    "спеть": {"imperfective": "петь", "type": "prefix", "prefix": "с-"},
    "брать": {"perfective": "взять", "type": "suppletive", "note": "Completely different roots (бер- vs возьм-)"},
    "взять": {"imperfective": "брать", "type": "suppletive", "note": "Completely different roots (возьм- vs бер-)"},
    "ждать": {"perfective": "подождать", "type": "prefix", "prefix": "по-"},
    "подождать": {"imperfective": "ждать", "type": "prefix", "prefix": "по-"},
    "звать": {"perfective": "позвать", "type": "prefix", "prefix": "по-"},
    "позвать": {"imperfective": "звать", "type": "prefix", "prefix": "по-"},
    "слать": {"perfective": "послать", "type": "prefix", "prefix": "по-"},
    "послать": {"imperfective": "слать", "type": "prefix", "prefix": "по-"},
    "вставать": {"perfective": "встать", "type": "suppletive", "note": "Different stem (встава- vs встан-)"},
    "встать": {"imperfective": "вставать", "type": "suppletive", "note": "Different stem (встан- vs встава-)"},
    "давать": {"perfective": "дать", "type": "suppletive", "note": "Different stems (дава- vs да-)"},
    "дать": {"imperfective": "давать", "type": "suppletive", "note": "Different stems (да- vs дава-)"},
    "узнавать": {"perfective": "узнать", "type": "suppletive", "note": "Different stem (узнава- vs узна-)"},
    "узнать": {"imperfective": "узнавать", "type": "suppletive", "note": "Different stem (узна- vs узнава-)"},
    "продавать": {"perfective": "продать", "type": "suppletive", "note": "Different stem (продава- vs прода-)"},
    "продать": {"imperfective": "продавать", "type": "suppletive", "note": "Different stem (прода- vs продава-)"},
    "создавать": {"perfective": "создать", "type": "suppletive", "note": "Different stem (создава- vs созда-)"},
    "создать": {"imperfective": "создавать", "type": "suppletive", "note": "Different stem (созда- vs создава-)"},
    "мыть": {"perfective": "помыть", "type": "prefix", "prefix": "по-"},
    "помыть": {"imperfective": "мыть", "type": "prefix", "prefix": "по-"},
    "крыть": {"perfective": "покрыть", "type": "prefix", "prefix": "по-"},
    "покрыть": {"imperfective": "крыть", "type": "prefix", "prefix": "по-"},
    "рыть": {"perfective": "вырыть", "type": "prefix", "prefix": "вы-"},
    "вырыть": {"imperfective": "рыть", "type": "prefix", "prefix": "вы-"},
    "открыть": {"imperfective": "открывать", "type": "suppletive", "note": "Different stem (откро- vs открыва-)"},
    "открывать": {"perfective": "открыть", "type": "suppletive", "note": "Different stem (открыва- vs откро-)"},
    "закрыть": {"imperfective": "закрывать", "type": "suppletive", "note": "Different stem (закро- vs закрыва-)"},
    "закрывать": {"perfective": "закрыть", "type": "suppletive", "note": "Different stem (закрыва- vs закро-)"},
    "есть": {"perfective": "съесть", "type": "prefix", "prefix": "с-"},
    "съесть": {"imperfective": "есть", "type": "prefix", "prefix": "с-"},
    "ошибиться": {"imperfective": "ошибаться", "type": "suppletive", "note": "Different stem (ошиб- vs ошиба-)"},
    "ошибаться": {"perfective": "ошибиться", "type": "suppletive", "note": "Different stem (ошиба- vs ошиб-)"},
    "ложиться": {"perfective": "лечь", "type": "suppletive", "note": "Completely different roots (лож- vs ляг-)"},
    "лечь": {"imperfective": "ложиться", "type": "suppletive", "note": "Completely different roots (ляг- vs лож-)"},
    "садиться": {"perfective": "сесть", "type": "suppletive", "note": "Different roots (сад- vs сяд-)"},
    "сесть": {"imperfective": "садиться", "type": "suppletive", "note": "Different roots (сяд- vs сад-)"},
    "смеяться": {"perfective": "засмеяться", "type": "prefix", "prefix": "за-"},
    "засмеяться": {"imperfective": "смеяться", "type": "prefix", "prefix": "за-"},
    "надеяться": {"perfective": "понадеяться", "type": "prefix", "prefix": "по-"},
    "понадеяться": {"imperfective": "надеяться", "type": "prefix", "prefix": "по-"},
    "кататься": {"perfective": "покататься", "type": "prefix", "prefix": "по-"},
    "покататься": {"imperfective": "кататься", "type": "prefix", "prefix": "по-"},
    "собираться": {"perfective": "собраться", "type": "suppletive", "note": "Different stem (собира- vs собер-)"},
    "собраться": {"imperfective": "собираться", "type": "suppletive", "note": "Different stem (собер- vs собира-)"},
    "казаться": {"perfective": "показаться", "type": "prefix", "prefix": "по-"},
    "показаться": {"imperfective": "казаться", "type": "prefix", "prefix": "по-"},
    "улыбаться": {"perfective": "улыбнуться", "type": "suppletive", "note": "Different suffix (-ба- vs -ну-)"},
    "улыбнуться": {"imperfective": "улыбаться", "type": "suppletive", "note": "Different suffix (-ну- vs -ба-)"},
    "купаться": {"perfective": "искупаться", "type": "prefix", "prefix": "ис-"},
    "искупаться": {"imperfective": "купаться", "type": "prefix", "prefix": "ис-"},
    "одеваться": {"perfective": "одеться", "type": "suppletive", "note": "Different stem (одева- vs оден-)"},
    "одеться": {"imperfective": "одеваться", "type": "suppletive", "note": "Different stem (оден- vs одева-)"},
    "умываться": {"perfective": "умыться", "type": "suppletive", "note": "Different stem (умыва- vs умо-)"},
    "умыться": {"imperfective": "умываться", "type": "suppletive", "note": "Different stem (умо- vs умыва-)"},
    "просыпаться": {"perfective": "проснуться", "type": "suppletive", "note": "Different stem (просыпа- vs просн-)"},
    "проснуться": {"imperfective": "просыпаться", "type": "suppletive", "note": "Different stem (просн- vs просыпа-)"},
    "замёрзнуть": {"imperfective": "замерзать", "type": "suppletive", "note": "Different suffix (-ну- vs -за-)"},
    "замерзать": {"perfective": "замёрзнуть", "type": "suppletive", "note": "Different suffix (-за- vs -ну-)"},
}

VERBS_NOT_IN_DICT_NEEDING_IMPERFECTIVE_PAIRS = {
    "почувствовать": "чувствовать",
    "заинтересовать": "интересовать",
    "поучаствовать": "участвовать",
    "просуществовать": "существовать",
    "порекомендовать": "рекомендовать",
    "повоевать": "воевать",
    "переночевать": "ночевать",
    "повторить": "повторять",
    "изучить": "изучать",
    "ответить": "отвечать",
    "спросить": "спрашивать",
    "бросить": "бросать",
    "кинуть": "кидать",
    "сломать": "ломать",
    "хватить": "хватать",
    "искупать": "купать",
    "опоздать": "опаздывать",
    "суметь": "уметь",
    "пожалеть": "жалеть",
    "похудеть": "худеть",
    "потолстеть": "толстеть",
    "успевать": "успеть",
    "поспевать": "поспеть",
    "созревать": "созреть",
    "побегать": "бегать",
    "поплавать": "плавать",
    "полетать": "летать",
    "полазать": "лазать",
    "поползать": "ползать",
    "поискать": "искать",
    "порезать": "резать",
    "намазать": "мазать",
    "заплакать": "плакать",
    "вспахать": "пахать",
    "поскакать": "скакать",
    "рассказывать": "рассказать",
    "нарисовать": "рисовать",
    "потанцевать": "танцевать",
    "поцеловать": "целовать",
    "посоветовать": "советовать",
    "потребовать": "требовать",
    "пробовать": "попробовать",
    "прыгать": "прыгнуть",
    "толкать": "толкнуть",
    "махать": "махнуть",
    "возвращать": "вернуть",
    "полюбить": "любить",
    "поносить": "носить",
    "сходить": "ходить",
    "попросить": "просить",
    "повозить": "возить",
    "заплатить": "платить",
    "закрутить": "крутить",
    "сварить": "варить",
    "подарить": "дарить",
    "поймать": "ловить",
    "поставить": "ставить",
    "потратить": "тратить",
    "пускать": "пустить",
    "прощать": "простить",
    "загрустить": "грустить",
    "почистить": "чистить",
    "поездить": "ездить",
    "объяснять": "объяснить",
    "посидеть": "сидеть",
    "провисеть": "висеть",
    "полететь": "лететь",
    "зашуметь": "шуметь",
    "возненавидеть": "ненавидеть",
    "потерпеть": "терпеть",
    "обижать": "обидеть",
    "позависеть": "зависеть",
    "завертеть": "вертеть",
    "подержать": "держать",
    "подышать": "дышать",
    "погнать": "гнать",
    "полежать": "лежать",
    "помолчать": "молчать",
    "прозвучать": "звучать",
    "поспать": "спать",
    "покупать": "купить",
    "заканчивать": "закончить",
    "побежать": "бежать",
    "захотеть": "хотеть",
    "поехать": "ехать",
    "пойти": "идти",
    "приходить": "прийти",
    "проходить": "пройти",
    "находить": "найти",
    "понести": "нести",
    "повезти": "везти",
    "повести": "вести",
    "поползти": "ползти",
    "вырасти": "расти",
    "зацвести": "цвести",
    "полезть": "лезть",
    "смочь": "мочь",
    "помогать": "помочь",
    "сберечь": "беречь",
    "испечь": "печь",
    "потечь": "течь",
    "посечь": "сечь",
    "сжечь": "жечь",
    "постричь": "стричь",
    "привлечь": "влечь",
    "побить": "бить",
    "выпить": "пить",
    "вылить": "лить",
    "сшить": "шить",
    "свить": "вить",
    "побрить": "брить",
    "прожить": "жить",
    "поплыть": "плыть",
    "прослыть": "слыть",
    "подождать": "ждать",
    "позвать": "звать",
    "послать": "слать",
    "помыть": "мыть",
    "покрыть": "крыть",
    "вырыть": "рыть",
    "открывать": "открыть",
    "закрывать": "закрыть",
    "съесть": "есть",
    "ошибаться": "ошибиться",
    "засмеяться": "смеяться",
    "понадеяться": "надеяться",
    "покататься": "кататься",
    "собраться": "собираться",
    "показаться": "казаться",
    "улыбнуться": "улыбаться",
    "искупаться": "купаться",
    "одеться": "одеваться",
    "умыться": "умываться",
    "проснуться": "просыпаться",
    "замерзать": "замёрзнуть",
    "закончить": "заканчивать",
}

def get_aspect_pair(verb):
    if verb in ASPECT_PAIRS:
        return ASPECT_PAIRS[verb]
    if verb in VERBS_NOT_IN_DICT_NEEDING_IMPERFECTIVE_PAIRS:
        pair = VERBS_NOT_IN_DICT_NEEDING_IMPERFECTIVE_PAIRS[verb]
        conj = ASPECT_PAIRS.get(pair)
        if conj and "perfective" in conj:
            return {"imperfective": pair, "type": "likely_prefix", "note": "Inferred from existing data"}
        return {"perfective": pair, "type": "likely_prefix", "note": "Inferred from existing data"}
    return None
